export enum TransactionType {
  INCOME_SALE = "INCOME_SALE",
  INCOME_TRANSFER_BRANCH = "INCOME_TRANSFER_BRANCH",
  INCOME_FROM_VOUCHER_CANCELLATION = "INCOME_FROM_VOUCHER_CANCELLATION",
  EXPENSE_FROM_VOUCHER_P_CANCELLATION = "EXPENSE_FROM_VOUCHER_P_CANCELLATION",
  EXPENSE_BY_CATEGORY = "EXPENSE_BY_CATEGORY",
  EXPENSE_EMPLOYEED = "EXPENSE_EMPLOYEED",
  EXPENSE_SUPPLIER = "EXPENSE_SUPPLIER",
  EXPENSE_TRANSFER_BRANCH = "EXPENSE_TRANSFER_BRANCH",
}
