export { default as Modal } from "./Modal/Modal";
export { default as TextModal } from "./Modal/TextModal";
export { default as RemiModal } from "./Modal/RemiModal";
// export { default as ConfirmationModalRemito } from "./Modal/ConfirmationModalRemito";
export { default as InvoicePaymentModal } from "./Modal/InvoicePaymentModal";
export { default as InvoiceModal } from "./Modal/InvoiceModal";
export { default as RegisterPaymentModal } from "./Modal/RegisterpaymentModal";
export { default as ContactCreateModal } from "./Modal/ContactCreateModal";
export { default as ProductSearchModal } from "./Modal/ProductSearchModal";
export { default as NotificationModal } from "./Modal/NotificationModal";
export { default as PasswordConfirmModal } from "./Modal/PasswordConfirmModal";
